# pytorch_lightning==1.8.6
seed_everything: 4444

data:
  class_path: vocos.dataset.VocosDataModule
  init_args:
    train_params:
      filelist_path: ./filelist.train
      sampling_rate: 24000
      num_samples: 16384
      batch_size: 16
      num_workers: 8

    val_params:
      filelist_path: ./filelist.val
      sampling_rate: 24000
      num_samples: 48384
      batch_size: 16
      num_workers: 8

model:
  class_path: vocos.experiment_distill.VocosDistillExp
  init_args:
    teacher_model_path: "logs/vocos/version_0" # Or path to your local pretrained model
    feature_distill_coeff: 40
    output_distill_coeff: 10
    phase_loss_coeff: 0.05
    sample_rate: 24000
    initial_learning_rate: 5e-4
    mel_loss_coeff: 45
    mrd_loss_coeff: 0.1
    num_warmup_steps: 0 
    pretrain_mel_steps: 0

    # automatic evaluation
    evaluate_utmos: true
    evaluate_pesq: true
    evaluate_periodicty: true

    feature_extractor:
      class_path: vocos.feature_extractors.MelSpectrogramFeatures
      init_args:
        sample_rate: 24000
        n_fft: 1024
        hop_length: 256
        n_mels: 100
        padding: center

    backbone:
      class_path: vocos.spiking_modelsv3_distill.SpikingVocosBackbone
      init_args:
        input_channels: 100
        dim: 512
        intermediate_dim: 1536
        num_layers: 8
        snn_timestep: 4

    head:
      class_path: vocos.heads.ISTFTHead
      init_args:
        dim: 512
        n_fft: 1024
        hop_length: 256
        padding: center

trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: logs/
      name: spikingv3-distill
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        filename: vocos_distill_checkpoint_{epoch}_{step}_{val_loss:.4f}
        save_top_k: 3
        save_last: true
    - class_path: vocos.helpers.GradNormCallback

  max_steps: 2000000
  limit_val_batches: 100
  accelerator: gpu
  strategy: ddp
  devices: [0]
  log_every_n_steps: 100 